### ISSUE TITLE
"It is also recommended disable some functions in your php settings."

### ISSUE THREAD

**Issue by jtsternberg** [jeremejazz/phppad#1]
But, what functions?

**Comment by jeremejazz** [comment]
Good question. Sorry I haven't maintained this for a long time. I intended to address to those who want to upload it publicly by recommending to disable the exploitable function. But publishing is probably the last thing you would do since there are no security filers as the program was intended to run locally as a REPL. I'll try to rephrase the statement on the next update perhaps.

**Comment by jeremejazz** [comment]
I've revised README.md. Thank you for your time.

**Comment by jtsternberg** [comment]
👍
